name: ghg
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10.13
  - pip=23.3.1
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - tqdm
  - tensorboard
  - scipy
  - scikit-image
  - pip:
    - opencv-python
    - taichi==1.5.0
    - yacs==0.1.8
    - open3d
    - trimesh
    - smplx
    - imageio
    - ninja
    - lpips
    - pytorch-fid