name: 'ghg'

restore_ckpt: 'weights/model_gaussian.pth'
finetune_ckpt: None
generator_ckpt: 'weights/model_inpaint.pth'

finetune_generator: False
num_out_scaffold: 4

lr: 0.0001
wdecay: 1e-5
batch_size: 1
num_steps: 100000

dataset:
  num_total_cams: 16
  num_inputs: 3
  test_input_view: [0, 6, 11]
  source_id: [0, 1]
  train_novel_id: [2, 3, 4]
  val_novel_id: [3]
  use_hr_img: False
  use_processed_data: False
  data_root: 'datasets/THuman'

raft:
  mixed_precision: True
  train_iters: 3
  val_iters: 3
  encoder_dims: [32, 48, 96]
  hidden_dims: [96, 96, 96]

gsnet:
  encoder_dims: [32, 48, 96]
  decoder_dims: [48, 64, 96]
  parm_head_dim: 32

record:
  loss_freq: 200
  eval_freq: 200
